// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MmaLegacy.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MmaLegacy.Api.Data.Migrations
{
    [DbContext(typeof(ContextoDoJogo))]
    [Migration("20260807001556_RankingDaCarreira")]
    partial class RankingDaCarreira
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MmaLegacy.Api.Domain.Carreira", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AnosComoCampeao")
                        .HasColumnType("integer");

                    b.Property<bool>("AposentouInvicto")
                        .HasColumnType("boolean");

                    b.Property<string>("CategoriaFinal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CinturoesConquistados")
                        .HasColumnType("integer");

                    b.Property<int>("DefesasDeCinturao")
                        .HasColumnType("integer");

                    b.Property<int>("Derrotas")
                        .HasColumnType("integer");

                    b.Property<int>("Empates")
                        .HasColumnType("integer");

                    b.Property<bool>("Encerrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("FoiDuploCampeao")
                        .HasColumnType("boolean");

                    b.Property<int>("IdadeDeAposentadoria")
                        .HasColumnType("integer");

                    b.Property<int>("IdadeDeEstreia")
                        .HasColumnType("integer");

                    b.Property<string>("Legado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaiorSequenciaDeVitorias")
                        .HasColumnType("integer");

                    b.Property<string>("MotivoDoEncerramento")
                        .HasColumnType("text");

                    b.Property<decimal>("OverallMaximo")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)");

                    b.Property<Guid>("PartidaId")
                        .HasColumnType("uuid");

                    b.Property<int>("PontuacaoDeLegado")
                        .HasColumnType("integer");

                    b.Property<int>("SequenciaAtualDeVitorias")
                        .HasColumnType("integer");

                    b.Property<int>("Vitorias")
                        .HasColumnType("integer");

                    b.Property<int>("VitoriasPorDecisao")
                        .HasColumnType("integer");

                    b.Property<int>("VitoriasPorFinalizacao")
                        .HasColumnType("integer");

                    b.Property<int>("VitoriasPorNocaute")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique();

                    b.ToTable("Carreiras", (string)null);
                });

            modelBuilder.Entity("MmaLegacy.Api.Domain.Lutador", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<bool>("EhLenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int?>("PosicaoNoRanking")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<bool>("SorteavelNoDraft")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("SorteavelNoDraft");

                    b.HasIndex("Categoria", "PosicaoNoRanking");

                    b.ToTable("Lutadores", (string)null);
                });

            modelBuilder.Entity("MmaLegacy.Api.Domain.Partida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelDeDificuldade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Facil");

                    b.Property<int>("PulosUsados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Partidas", (string)null);
                });

            modelBuilder.Entity("MmaLegacy.Api.Domain.Carreira", b =>
                {
                    b.HasOne("MmaLegacy.Api.Domain.Partida", null)
                        .WithOne("Carreira")
                        .HasForeignKey("MmaLegacy.Api.Domain.Carreira", "PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MmaLegacy.Api.Domain.EstadoDaCarreira", "Estado", b1 =>
                        {
                            b1.Property<Guid>("CarreiraId")
                                .HasColumnType("uuid");

                            b1.Property<int>("AjusteDeOverallDoAdversario")
                                .HasColumnType("integer")
                                .HasColumnName("AjusteDeOverallDoAdversario");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CategoriaAtual");

                            b1.Property<int>("CompromissosNaTemporada")
                                .HasColumnType("integer")
                                .HasColumnName("CompromissosNaTemporada");

                            b1.Property<int>("DefesasNaCategoria")
                                .HasColumnType("integer")
                                .HasColumnName("DefesasNaCategoria");

                            b1.Property<int>("DerrotasSeguidas")
                                .HasColumnType("integer")
                                .HasColumnName("DerrotasSeguidas");

                            b1.Property<bool>("EhCampeao")
                                .HasColumnType("boolean")
                                .HasColumnName("EhCampeao");

                            b1.Property<string>("Etapa")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Etapa");

                            b1.Property<int>("Idade")
                                .HasColumnType("integer")
                                .HasColumnName("IdadeAtual");

                            b1.Property<bool>("JaMudouDeCategoria")
                                .HasColumnType("boolean")
                                .HasColumnName("JaMudouDeCategoria");

                            b1.Property<int>("NocautesSofridos")
                                .HasColumnType("integer")
                                .HasColumnName("NocautesSofridos");

                            b1.Property<int>("NocautesSofridosNoAno")
                                .HasColumnType("integer")
                                .HasColumnName("NocautesSofridosNoAno");

                            b1.Property<decimal>("OverallMaximo")
                                .HasPrecision(4, 1)
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("OverallMaximoDoEstado");

                            b1.Property<int>("Passo")
                                .HasColumnType("integer")
                                .HasColumnName("Passo");

                            b1.Property<int?>("PosicaoNoRanking")
                                .HasColumnType("integer")
                                .HasColumnName("PosicaoNoRanking");

                            b1.Property<int>("RecusasSeguidas")
                                .HasColumnType("integer")
                                .HasColumnName("RecusasSeguidas");

                            b1.Property<int>("VezesDispensado")
                                .HasColumnType("integer")
                                .HasColumnName("VezesDispensado");

                            b1.Property<int>("VitoriasNaEtapa")
                                .HasColumnType("integer")
                                .HasColumnName("VitoriasNaEtapa");

                            b1.HasKey("CarreiraId");

                            b1.ToTable("Carreiras");

                            b1.WithOwner()
                                .HasForeignKey("CarreiraId");

                            b1.OwnsOne("MmaLegacy.Api.Domain.Atributos", "Atributos", b2 =>
                                {
                                    b2.Property<Guid>("EstadoDaCarreiraCarreiraId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Cardio")
                                        .HasColumnType("integer")
                                        .HasColumnName("Cardio");

                                    b2.Property<int>("InteligenciaDeLuta")
                                        .HasColumnType("integer")
                                        .HasColumnName("InteligenciaDeLuta");

                                    b2.Property<int>("JiuJitsu")
                                        .HasColumnType("integer")
                                        .HasColumnName("JiuJitsu");

                                    b2.Property<int>("Potencia")
                                        .HasColumnType("integer")
                                        .HasColumnName("Potencia");

                                    b2.Property<int>("Resistencia")
                                        .HasColumnType("integer")
                                        .HasColumnName("Resistencia");

                                    b2.Property<int>("Striking")
                                        .HasColumnType("integer")
                                        .HasColumnName("Striking");

                                    b2.Property<int>("Velocidade")
                                        .HasColumnType("integer")
                                        .HasColumnName("Velocidade");

                                    b2.Property<int>("Wrestling")
                                        .HasColumnType("integer")
                                        .HasColumnName("Wrestling");

                                    b2.HasKey("EstadoDaCarreiraCarreiraId");

                                    b2.ToTable("Carreiras");

                                    b2.WithOwner()
                                        .HasForeignKey("EstadoDaCarreiraCarreiraId");
                                });

                            b1.Navigation("Atributos")
                                .IsRequired();
                        });

                    b.OwnsMany("MmaLegacy.Api.Domain.LutaDaCarreira", "Lutas", b1 =>
                        {
                            b1.Property<Guid>("CarreiraId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordem")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordem"));

                            b1.Property<string>("Adversario")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<bool>("DefesaDeCinturao")
                                .HasColumnType("boolean");

                            b1.Property<bool>("DisputaDeCinturao")
                                .HasColumnType("boolean");

                            b1.Property<string>("EstiloDoAdversario")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Idade")
                                .HasColumnType("integer");

                            b1.Property<string>("Metodo")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Organizacao")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("OverallDoAdversario")
                                .HasPrecision(4, 1)
                                .HasColumnType("numeric(4,1)");

                            b1.Property<string>("Resultado")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("RoundDoEncerramento")
                                .HasColumnType("integer");

                            b1.Property<int>("RoundsProgramados")
                                .HasColumnType("integer");

                            b1.HasKey("CarreiraId", "Ordem");

                            b1.ToTable("LutasDaCarreira", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CarreiraId");
                        });

                    b.OwnsMany("MmaLegacy.Api.Domain.OfertaDeLuta", "Ofertas", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Adversario")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<Guid>("CarreiraId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CartelDoAdversario")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Categoria")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Chamada")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.Property<bool>("DefesaDeCinturao")
                                .HasColumnType("boolean");

                            b1.Property<bool>("DisputaDeCinturao")
                                .HasColumnType("boolean");

                            b1.Property<int>("Indice")
                                .HasColumnType("integer");

                            b1.Property<string>("Organizacao")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int?>("PosicaoDoAdversario")
                                .HasColumnType("integer");

                            b1.Property<int>("RoundsProgramados")
                                .HasColumnType("integer");

                            b1.Property<string>("SlugDoAdversario")
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.HasKey("Id");

                            b1.HasIndex("CarreiraId");

                            b1.ToTable("OfertasDeLuta", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CarreiraId");

                            b1.OwnsOne("MmaLegacy.Api.Domain.Atributos", "AtributosDoAdversario", b2 =>
                                {
                                    b2.Property<Guid>("OfertaDeLutaId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Cardio")
                                        .HasColumnType("integer")
                                        .HasColumnName("Cardio");

                                    b2.Property<int>("InteligenciaDeLuta")
                                        .HasColumnType("integer")
                                        .HasColumnName("InteligenciaDeLuta");

                                    b2.Property<int>("JiuJitsu")
                                        .HasColumnType("integer")
                                        .HasColumnName("JiuJitsu");

                                    b2.Property<int>("Potencia")
                                        .HasColumnType("integer")
                                        .HasColumnName("Potencia");

                                    b2.Property<int>("Resistencia")
                                        .HasColumnType("integer")
                                        .HasColumnName("Resistencia");

                                    b2.Property<int>("Striking")
                                        .HasColumnType("integer")
                                        .HasColumnName("Striking");

                                    b2.Property<int>("Velocidade")
                                        .HasColumnType("integer")
                                        .HasColumnName("Velocidade");

                                    b2.Property<int>("Wrestling")
                                        .HasColumnType("integer")
                                        .HasColumnName("Wrestling");

                                    b2.HasKey("OfertaDeLutaId");

                                    b2.ToTable("OfertasDeLuta");

                                    b2.WithOwner()
                                        .HasForeignKey("OfertaDeLutaId");
                                });

                            b1.Navigation("AtributosDoAdversario")
                                .IsRequired();
                        });

                    b.Navigation("Estado")
                        .IsRequired();

                    b.Navigation("Lutas");

                    b.Navigation("Ofertas");
                });

            modelBuilder.Entity("MmaLegacy.Api.Domain.Lutador", b =>
                {
                    b.OwnsOne("MmaLegacy.Api.Domain.Atributos", "Atributos", b1 =>
                        {
                            b1.Property<Guid>("LutadorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Cardio")
                                .HasColumnType("integer")
                                .HasColumnName("Cardio");

                            b1.Property<int>("InteligenciaDeLuta")
                                .HasColumnType("integer")
                                .HasColumnName("InteligenciaDeLuta");

                            b1.Property<int>("JiuJitsu")
                                .HasColumnType("integer")
                                .HasColumnName("JiuJitsu");

                            b1.Property<int>("Potencia")
                                .HasColumnType("integer")
                                .HasColumnName("Potencia");

                            b1.Property<int>("Resistencia")
                                .HasColumnType("integer")
                                .HasColumnName("Resistencia");

                            b1.Property<int>("Striking")
                                .HasColumnType("integer")
                                .HasColumnName("Striking");

                            b1.Property<int>("Velocidade")
                                .HasColumnType("integer")
                                .HasColumnName("Velocidade");

                            b1.Property<int>("Wrestling")
                                .HasColumnType("integer")
                                .HasColumnName("Wrestling");

                            b1.HasKey("LutadorId");

                            b1.ToTable("Lutadores");

                            b1.WithOwner()
                                .HasForeignKey("LutadorId");
                        });

                    b.Navigation("Atributos")
                        .IsRequired();
                });

            modelBuilder.Entity("MmaLegacy.Api.Domain.Partida", b =>
                {
                    b.OwnsOne("MmaLegacy.Api.Domain.FichaDeInscricao", "Ficha", b1 =>
                        {
                            b1.Property<Guid>("PartidaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Apelido")
                                .IsRequired()
                                .HasMaxLength(30)
                                .HasColumnType("character varying(30)")
                                .HasColumnName("Apelido");

                            b1.Property<string>("BaseDeLuta")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BaseDeLuta");

                            b1.Property<string>("CategoriaDePeso")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CategoriaDePeso");

                            b1.Property<int>("IdadeInicial")
                                .HasColumnType("integer")
                                .HasColumnName("IdadeInicial");

                            b1.Property<string>("Nacionalidade")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("Nacionalidade");

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("Nome");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.OwnsOne("MmaLegacy.Api.Domain.LutadorCriado", "Lutador", b1 =>
                        {
                            b1.Property<Guid>("PartidaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Estilo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Estilo");

                            b1.Property<decimal>("Overall")
                                .HasPrecision(4, 1)
                                .HasColumnType("numeric(4,1)")
                                .HasColumnName("Overall");

                            b1.HasKey("PartidaId");

                            b1.ToTable("Partidas");

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");

                            b1.OwnsOne("MmaLegacy.Api.Domain.Atributos", "Atributos", b2 =>
                                {
                                    b2.Property<Guid>("LutadorCriadoPartidaId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Cardio")
                                        .HasColumnType("integer")
                                        .HasColumnName("Cardio");

                                    b2.Property<int>("InteligenciaDeLuta")
                                        .HasColumnType("integer")
                                        .HasColumnName("InteligenciaDeLuta");

                                    b2.Property<int>("JiuJitsu")
                                        .HasColumnType("integer")
                                        .HasColumnName("JiuJitsu");

                                    b2.Property<int>("Potencia")
                                        .HasColumnType("integer")
                                        .HasColumnName("Potencia");

                                    b2.Property<int>("Resistencia")
                                        .HasColumnType("integer")
                                        .HasColumnName("Resistencia");

                                    b2.Property<int>("Striking")
                                        .HasColumnType("integer")
                                        .HasColumnName("Striking");

                                    b2.Property<int>("Velocidade")
                                        .HasColumnType("integer")
                                        .HasColumnName("Velocidade");

                                    b2.Property<int>("Wrestling")
                                        .HasColumnType("integer")
                                        .HasColumnName("Wrestling");

                                    b2.HasKey("LutadorCriadoPartidaId");

                                    b2.ToTable("Partidas");

                                    b2.WithOwner()
                                        .HasForeignKey("LutadorCriadoPartidaId");
                                });

                            b1.Navigation("Atributos")
                                .IsRequired();
                        });

                    b.OwnsMany("MmaLegacy.Api.Domain.RodadaDeDraft", "Rodadas", b1 =>
                        {
                            b1.Property<Guid>("PartidaId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ordem")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Ordem"));

                            b1.Property<string>("HabilidadeEscolhida")
                                .HasColumnType("text");

                            b1.Property<Guid>("LutadorId")
                                .HasColumnType("uuid");

                            b1.Property<string>("LutadorNome")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("character varying(80)");

                            b1.Property<int?>("NotaObtida")
                                .HasColumnType("integer");

                            b1.HasKey("PartidaId", "Ordem");

                            b1.ToTable("RodadasDeDraft", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PartidaId");
                        });

                    b.Navigation("Ficha")
                        .IsRequired();

                    b.Navigation("Lutador");

                    b.Navigation("Rodadas");
                });

            modelBuilder.Entity("MmaLegacy.Api.Domain.Partida", b =>
                {
                    b.Navigation("Carreira");
                });
#pragma warning restore 612, 618
        }
    }
}
